#bash script

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -40,14 +40,17 @@
       steps:
         - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1
 
-        - name: Test example
-          shell: "C:/Program Files/Git/bin/bash.exe --noprofile --norc -e -o pipefail {0}"
+        - name: Test example          
+          shell: "C:/Program Files/Git/bin/bash.exe"
           env:
             TF_IN_AUTOMATION: 1
             TF_VAR_enable_telemetry: false
           run: |
             echo "Running Bash version check"
-            bash --version  # Prints the version of the current shell (bash)
+            set -e  # Enable 'exit on error'
+            set -o pipefail  # Ensures pipelines fail if any command fails
+            bash --noprofile --norc --version  # Prints the version of Bash without loading profiles
+            
         #   shell: bash #"C:/Program Files/Git/bin/bash.exe" ## --noprofile --norc -e -o pipefail {0}"
         #  # env:
         # #    BASH_PATH: "C:/Program Files/Git/bin/bash.exe"
