#Updated details

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -1,99 +1,189 @@
 ---
-name: e2e test
+  name: e2e test
+  
+  on:
+    pull_request:
+      types: ['opened', 'reopened', 'synchronize']
+    merge_group:
+    workflow_dispatch:
+  
+  permissions:
+    contents: read
+    id-token: write
+  
+  jobs:
+    getexamples:
+      if: github.event.repository.name != 'terraform-azurerm-avm-template'
+      runs-on: ubuntu-latest
+      outputs:
+        examples: ${{ steps.getexamples.outputs.examples }}
+      steps:
+        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
+        - name: get examples
+          id: getexamples
+          uses: Azure/terraform-azurerm-avm-template/.github/actions/e2e-getexamples@main
+          with:
+            github-token: ${{ secrets.GITHUB_TOKEN }}
+  
+    testexamples:
+      if: github.event.repository.name != 'terraform-azurerm-avm-template'
+      #runs-on: [ self-hosted, 1ES.Pool=ff314ac9fce031b9e7f5dde283f515666e148ae7 ]
+      runs-on: [ self-hosted, Linux ]
+      needs: getexamples
+      environment: test
+      env:
+        TF_IN_AUTOMATION: 1
+        TF_VAR_enable_telemetry: false
+        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
+      strategy:
+        matrix:
+          example: ${{ fromJson(needs.getexamples.outputs.examples) }}
+        fail-fast: false
+      steps:
+        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
+  
+        # - name: Set up Terraform
+        #   run: |
+        #     sudo apt-get update -y
+        #     sudo apt-get install -y software-properties-common
+        #     sudo apt-add-repository --yes --update ppa:ansible/ansible
+        #     sudo apt-get update -y
+        #     sudo apt-get install -y terraform
+  
+        - name: Initialize Terraform for example
+          run: |
+            terraform init -backend=false -reconfigure
+          working-directory: ${{ matrix.example }}
+  
+        - name: Validate Terraform example
+          run: |
+            terraform validate
+          working-directory: ${{ matrix.example }}
+  
+        - name: Plan Terraform example
+          run: |
+            terraform plan -input=false -out=tfplan
+          working-directory: ${{ matrix.example }}
+  
+        - name: Apply Terraform example
+          run: |
+            terraform apply -input=false tfplan
+          working-directory: ${{ matrix.example }}
+  
+        - name: Destroy Terraform example
+          if: always()
+          run: |
+            terraform destroy -auto-approve
+          working-directory: ${{ matrix.example }}
+  
+    testexamplescomplete:
+      if: github.event.repository.name != 'terraform-azurerm-avm-template'
+      runs-on: ubuntu-latest
+      needs: testexamples
+      steps:
+        - run: echo "All tests passed"
+  
 
-on:
-  pull_request:
-    types: ['opened', 'reopened', 'synchronize']
-  merge_group:
-  workflow_dispatch:
 
-permissions:
-  contents: read
-  id-token: write
+# ---
+# name: e2e test
 
-jobs:
-  getexamples:
-    if: github.event.repository.name != 'terraform-azurerm-avm-template'
-    runs-on: ubuntu-latest
-    outputs:
-      examples: ${{ steps.getexamples.outputs.examples }}
-    steps:
-      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
-      - name: get examples
-        id: getexamples
-        uses: Azure/terraform-azurerm-avm-template/.github/actions/e2e-getexamples@main
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
+# on:
+#   pull_request:
+#     types: ['opened', 'reopened', 'synchronize']
+#   merge_group:
+#   workflow_dispatch:
 
-  testexamples:
-    if: github.event.repository.name != 'terraform-azurerm-avm-template'
-    runs-on: [ self-hosted, 1ES.Pool=ff314ac9fce031b9e7f5dde283f515666e148ae7 ]
-    needs: getexamples
-    environment: test
-    env:
-      TF_IN_AUTOMATION: 1
-      TF_VAR_enable_telemetry: false
-    strategy:
-      matrix:
-        example: ${{ fromJson(needs.getexamples.outputs.examples) }}
-      fail-fast: false
-    steps:
-      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
+# permissions:
+#   contents: read
+#   id-token: write
 
-      - name: Test example
-        shell: bash
-        env:
-          SECRETS_CONTEXT: ${{ toJson(secrets) }}
-          VARS_CONTEXT: ${{ toJson(vars) }}
-        run: |
-          set -e
-           MAX_RETRIES=10
-          RETRY_COUNT=0
-          until [ $RETRY_COUNT -ge $MAX_RETRIES ]
-          do
-            az login --identity --username $MSI_ID > /dev/null && break
-            RETRY_COUNT=$[$RETRY_COUNT+1]
-            sleep 10
-          done
-          if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
-            echo "Failed to login after $MAX_RETRIES attempts."
-            exit 1
-          fi
+# jobs:
+#   getexamples:
+#     if: github.event.repository.name != 'terraform-azurerm-avm-template'
+#     runs-on: ubuntu-latest
+#     outputs:
+#       examples: ${{ steps.getexamples.outputs.examples }}
+#     steps:
+#       - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
+#       - name: get examples
+#         id: getexamples
+#         uses: Azure/terraform-azurerm-avm-template/.github/actions/e2e-getexamples@main
+#         with:
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
 
-          declare -A secrets
-          eval "$(echo $SECRETS_CONTEXT | jq -r 'to_entries[] | @sh "secrets[\(.key|tostring)]=\(.value|tostring)"')"
+#   testexamples:
+#     if: github.event.repository.name != 'terraform-azurerm-avm-template'
+#     runs-on: [ self-hosted, 1ES.Pool=ff314ac9fce031b9e7f5dde283f515666e148ae7 ]
+#     needs: getexamples
+#     environment: test
+#     env:
+#       TF_IN_AUTOMATION: 1
+#       TF_VAR_enable_telemetry: false
+#     strategy:
+#       matrix:
+#         example: ${{ fromJson(needs.getexamples.outputs.examples) }}
+#       fail-fast: false
+#     steps:
+#       - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
 
-          declare -A variables
-          eval "$(echo $VARS_CONTEXT | jq -r 'to_entries[] | @sh "variables[\(.key|tostring)]=\(.value|tostring)"')"
+#       - name: Test example
+#         shell: bash
+#         env:
+#           SECRETS_CONTEXT: ${{ toJson(secrets) }}
+#           VARS_CONTEXT: ${{ toJson(vars) }}
+#         run: |
+#           set -e
+#            MAX_RETRIES=10
+#           RETRY_COUNT=0
+#           until [ $RETRY_COUNT -ge $MAX_RETRIES ]
+#           do
+#             az login --identity --username $MSI_ID > /dev/null && break
+#             RETRY_COUNT=$[$RETRY_COUNT+1]
+#             sleep 10
+#           done
+#           if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+#             echo "Failed to login after $MAX_RETRIES attempts."
+#             exit 1
+#           fi
 
-          for key in "${!secrets[@]}"; do
-            if [[ $key = \TF_VAR_* ]]; then
-              lowerKey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
-              finalKey=${lowerKey/tf_var_/TF_VAR_}
-              export "$finalKey"="${secrets[$key]}"
-            fi
-          done
+#           declare -A secrets
+#           eval "$(echo $SECRETS_CONTEXT | jq -r 'to_entries[] | @sh "secrets[\(.key|tostring)]=\(.value|tostring)"')"
 
-          for key in "${!variables[@]}"; do
-            if [[ $key = \TF_VAR_* ]]; then
-              lowerKey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
-              finalKey=${lowerKey/tf_var_/TF_VAR_}
-              export "$finalKey"="${variables[$key]}"
-            fi
-          done
+#           declare -A variables
+#           eval "$(echo $VARS_CONTEXT | jq -r 'to_entries[] | @sh "variables[\(.key|tostring)]=\(.value|tostring)"')"
 
-          echo -e "Custom environment variables:\n$(env | grep TF_VAR_ | grep -v ' "TF_VAR_')"
+#           for key in "${!secrets[@]}"; do
+#             if [[ $key = \TF_VAR_* ]]; then
+#               lowerKey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
+#               finalKey=${lowerKey/tf_var_/TF_VAR_}
+#               export "$finalKey"="${secrets[$key]}"
+#             fi
+#           done
 
-          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
-          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
-          export ARM_CLIENT_ID=$(az identity list | jq -r --arg MSI_ID "$MSI_ID" '.[] | select(.principalId == $MSI_ID) | .clientId')
-          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src -w /src --network=host -e TF_IN_AUTOMATION -e TF_VAR_enable_telemetry -e AVM_MOD_PATH=/src -e AVM_EXAMPLE=${{ matrix.example }} -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_CLIENT_ID -e ARM_USE_MSI=true --env-file <(env | grep TF_VAR_ | grep -v ' "TF_VAR_') mcr.microsoft.com/azterraform:latest make test-example
+#           for key in "${!variables[@]}"; do
+#             if [[ $key = \TF_VAR_* ]]; then
+#               lowerKey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
+#               finalKey=${lowerKey/tf_var_/TF_VAR_}
+#               export "$finalKey"="${variables[$key]}"
+#             fi
+#           done
 
-  # This job is only run when all the previous jobs are successful.
-  # We can use it for PR validation to ensure all examples have completed.
-  testexamplescomplete:
-    if: github.event.repository.name != 'terraform-azurerm-avm-template'
-    runs-on: ubuntu-latest
-    needs: testexamples
-    steps:
-      - run: echo "All tests passed"
+#           echo -e "Custom environment variables:\n$(env | grep TF_VAR_ | grep -v ' "TF_VAR_')"
+
+#           export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
+#           export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
+#           export ARM_CLIENT_ID=$(az identity list | jq -r --arg MSI_ID "$MSI_ID" '.[] | select(.principalId == $MSI_ID) | .clientId')
+#           docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src -w /src --network=host -e TF_IN_AUTOMATION -e TF_VAR_enable_telemetry -e AVM_MOD_PATH=/src -e AVM_EXAMPLE=${{ matrix.example }} -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_CLIENT_ID -e ARM_USE_MSI=true --env-file <(env | grep TF_VAR_ | grep -v ' "TF_VAR_') mcr.microsoft.com/azterraform:latest make test-example
+
+#   # This job is only run when all the previous jobs are successful.
+#   # We can use it for PR validation to ensure all examples have completed.
+#   testexamplescomplete:
+#     if: github.event.repository.name != 'terraform-azurerm-avm-template'
+#     runs-on: ubuntu-latest
+#     needs: testexamples
+#     steps:
+#       - run: echo "All tests passed"
