#added script

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -42,7 +42,7 @@
     
     testexamples:
       if: github.event.repository.name != 'terraform-azurerm-avm-template'
-      runs-on: self-hosted
+      runs-on: [ self-hosted, 1ES.Pool=ff314ac9fce031b9e7f5dde283f515666e148ae7 ]
       needs: getexamples
       environment: test
       env:
@@ -55,60 +55,63 @@
       steps:
         - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1
 
-        - name: Test example
-          shell: cmd
-          env:
-            SECRETS_CONTEXT: ${{ toJson(secrets) }}
-            VARS_CONTEXT: ${{ toJson(vars) }}
+        - name: Write Bash script to file
+          shell: bash
           run: |
-            echo @echo off > run_bash_commands.bat
-            echo echo Running Bash version check via cmd >> run_bash_commands.bat
-            echo "C:/Program Files/Git/bin/bash.exe" --noprofile --norc --version >> run_bash_commands.bat
-            
-            echo echo Attempting az login >> run_bash_commands.bat
-            echo "C:/Program Files/Git/bin/bash.exe" -c ' \
-              set -e; \
-              MAX_RETRIES=10; \
-              RETRY_COUNT=0; \
-              until [ $RETRY_COUNT -ge $MAX_RETRIES ]; do \
-                az login --identity --username $MSI_ID > /dev/null && break; \
-                RETRY_COUNT=$((RETRY_COUNT+1)); \
-                sleep 10; \
-              done; \
-              if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then \
-                echo Failed to login after $MAX_RETRIES attempts.; \
-                exit 1; \
-              fi' >> run_bash_commands.bat
+            cat <<'EOF' > run_bash_commands.sh
+            #!/bin/bash
+            set -e
 
-            echo echo Declaring and exporting environment variables >> run_bash_commands.bat
-            echo "C:/Program Files/Git/bin/bash.exe" -c ' \
-              declare -A secrets; \
-              eval \"$(echo $SECRETS_CONTEXT | jq -r 'to_entries[] | @sh \"secrets[\(.key|tostring)]=\(.value|tostring)\"')\"; \
-              declare -A variables; \
-              eval \"$(echo $VARS_CONTEXT | jq -r 'to_entries[] | @sh \"variables[\(.key|tostring)]=\(.value|tostring)\"')\"; \
-              for key in \"\${!secrets[@]}\"; do \
-                if [[ $key = \TF_VAR_* ]]; then \
-                  lowerKey=\$(echo \"$key\" | tr '[:upper:]' '[:lower:]'); \
-                  finalKey=\${lowerKey/tf_var_/TF_VAR_}; \
-                  export \"$finalKey\"=\"\${secrets[$key]}\"; \
-                fi; \
-              done; \
-              for key in \"\${!variables[@]}\"; do \
-                if [[ $key = \TF_VAR_* ]]; then \
-                  lowerKey=\$(echo \"$key\" | tr '[:upper:]' '[:lower:]'); \
-                  finalKey=\${lowerKey/tf_var_/TF_VAR_}; \
-                  export \"$finalKey\"=\"\${variables[$key]}\"; \
-                fi; \
-              done' >> run_bash_commands.bat
+            MAX_RETRIES=10
+            RETRY_COUNT=0
 
-            echo echo Executing Docker command >> run_bash_commands.bat
-            echo "C:/Program Files/Git/bin/bash.exe" -c ' \
-              export ARM_SUBSCRIPTION_ID=\$(az login --identity --username $MSI_ID | jq -r \".[0] | .id\"); \
-              export ARM_TENANT_ID=\$(az login --identity --username $MSI_ID | jq -r \".[0] | .tenantId\"); \
-              export ARM_CLIENT_ID=\$(az identity list | jq -r --arg MSI_ID \"$MSI_ID\" \".[] | select(.principalId == \$MSI_ID) | .clientId\"); \
-              docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v \$(pwd):/src -w /src --network=host -e TF_IN_AUTOMATION -e TF_VAR_enable_telemetry -e AVM_MOD_PATH=/src -e AVM_EXAMPLE=${{ matrix.example }} -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_CLIENT_ID -e ARM_USE_MSI=true --env-file <(env | grep TF_VAR_ | grep -v \" TF_VAR_\") mcr.microsoft.com/azterraform:latest make test-example' >> run_bash_commands.bat
-            
-            call run_bash_commands.bat
+            until [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
+              az login --identity --username $MSI_ID > /dev/null && break
+              RETRY_COUNT=$((RETRY_COUNT+1))
+              sleep 10
+            done
+
+            if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+              echo "Failed to login after $MAX_RETRIES attempts."
+              exit 1
+            fi
+
+            declare -A secrets
+            eval "$(echo $SECRETS_CONTEXT | jq -r 'to_entries[] | @sh "secrets[\(.key|tostring)]=\(.value|tostring)"')"
+
+            declare -A variables
+            eval "$(echo $VARS_CONTEXT | jq -r 'to_entries[] | @sh "variables[\(.key|tostring)]=\(.value|tostring)"')"
+
+            for key in "${!secrets[@]}"; do
+              if [[ $key == TF_VAR_* ]]; then
+                lowerKey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
+                finalKey=${lowerKey/tf_var_/TF_VAR_}
+                export "$finalKey"="${secrets[$key]}"
+              fi
+            done
+
+            for key in "${!variables[@]}"; do
+              if [[ $key == TF_VAR_* ]]; then
+                lowerKey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
+                finalKey=${lowerKey/tf_var_/TF_VAR_}
+                export "$finalKey"="${variables[$key]}"
+              fi
+            done
+
+            export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
+            export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
+            export ARM_CLIENT_ID=$(az identity list | jq -r --arg MSI_ID "$MSI_ID" '.[] | select(.principalId == $MSI_ID) | .clientId')
+
+            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src -w /src --network=host \
+              -e TF_IN_AUTOMATION -e TF_VAR_enable_telemetry -e AVM_MOD_PATH=/src -e AVM_EXAMPLE=${{ matrix.example }} \
+              -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_CLIENT_ID -e ARM_USE_MSI=true \
+              --env-file <(env | grep TF_VAR_ | grep -v ' "TF_VAR_"') mcr.microsoft.com/azterraform:latest make test-example
+            EOF
+
+        - name: Run Git Bash script
+          shell: bash
+          run: |
+            bash run_bash_commands.sh
 
 
 
