#added data

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -55,58 +55,69 @@
       steps:
         - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1
 
-        - name: Write Bash script to file
-          shell: bash
+        - name: Run Git Bash script
+          shell: "C:/Program Files/Git/bin/bash.exe --noprofile --norc -e -o pipefail"
+          env:
+            TF_IN_AUTOMATION: 1
+            TF_VAR_enable_telemetry: false
           run: |
-            cat <<'EOF' > run_bash_commands.sh
-            #!/bin/bash
-            set -e
-
-            MAX_RETRIES=10
-            RETRY_COUNT=0
-
-            until [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
-              az login --identity --username $MSI_ID > /dev/null && break
-              RETRY_COUNT=$((RETRY_COUNT+1))
-              sleep 10
-            done
-
-            if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
-              echo "Failed to login after $MAX_RETRIES attempts."
-              exit 1
-            fi
-
-            declare -A secrets
-            eval "$(echo $SECRETS_CONTEXT | jq -r 'to_entries[] | @sh "secrets[\(.key|tostring)]=\(.value|tostring)"')"
-
-            declare -A variables
-            eval "$(echo $VARS_CONTEXT | jq -r 'to_entries[] | @sh "variables[\(.key|tostring)]=\(.value|tostring)"')"
-
-            for key in "${!secrets[@]}"; do
-              if [[ $key == TF_VAR_* ]]; then
-                lowerKey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
-                finalKey=${lowerKey/tf_var_/TF_VAR_}
-                export "$finalKey"="${secrets[$key]}"
-              fi
-            done
-
-            for key in "${!variables[@]}"; do
-              if [[ $key == TF_VAR_* ]]; then
-                lowerKey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
-                finalKey=${lowerKey/tf_var_/TF_VAR_}
-                export "$finalKey"="${variables[$key]}"
-              fi
-            done
-
-            export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
-            export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
-            export ARM_CLIENT_ID=$(az identity list | jq -r --arg MSI_ID "$MSI_ID" '.[] | select(.principalId == $MSI_ID) | .clientId')
-
             docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src -w /src --network=host \
-              -e TF_IN_AUTOMATION -e TF_VAR_enable_telemetry -e AVM_MOD_PATH=/src -e AVM_EXAMPLE=${{ matrix.example }} \
+              -e TF_IN_AUTOMATION -e TF_VAR_enable_telemetry -e AVM_MOD_PATH=/src -e AVM_EXAMPLE=default \
               -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_CLIENT_ID -e ARM_USE_MSI=true \
               --env-file <(env | grep TF_VAR_ | grep -v ' "TF_VAR_"') mcr.microsoft.com/azterraform:latest make test-example
-            EOF
+
+        # - name: Write Bash script to file
+        #   shell: bash
+        #   run: |
+        #     cat <<'EOF' > run_bash_commands.sh
+        #     #!/bin/bash
+        #     set -e
+
+        #     MAX_RETRIES=10
+        #     RETRY_COUNT=0
+
+        #     until [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
+        #       az login --identity --username $MSI_ID > /dev/null && break
+        #       RETRY_COUNT=$((RETRY_COUNT+1))
+        #       sleep 10
+        #     done
+
+        #     if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+        #       echo "Failed to login after $MAX_RETRIES attempts."
+        #       exit 1
+        #     fi
+
+        #     declare -A secrets
+        #     eval "$(echo $SECRETS_CONTEXT | jq -r 'to_entries[] | @sh "secrets[\(.key|tostring)]=\(.value|tostring)"')"
+
+        #     declare -A variables
+        #     eval "$(echo $VARS_CONTEXT | jq -r 'to_entries[] | @sh "variables[\(.key|tostring)]=\(.value|tostring)"')"
+
+        #     for key in "${!secrets[@]}"; do
+        #       if [[ $key == TF_VAR_* ]]; then
+        #         lowerKey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
+        #         finalKey=${lowerKey/tf_var_/TF_VAR_}
+        #         export "$finalKey"="${secrets[$key]}"
+        #       fi
+        #     done
+
+        #     for key in "${!variables[@]}"; do
+        #       if [[ $key == TF_VAR_* ]]; then
+        #         lowerKey=$(echo "$key" | tr '[:upper:]' '[:lower:]')
+        #         finalKey=${lowerKey/tf_var_/TF_VAR_}
+        #         export "$finalKey"="${variables[$key]}"
+        #       fi
+        #     done
+
+        #     export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
+        #     export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
+        #     export ARM_CLIENT_ID=$(az identity list | jq -r --arg MSI_ID "$MSI_ID" '.[] | select(.principalId == $MSI_ID) | .clientId')
+
+        #     docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src -w /src --network=host \
+        #       -e TF_IN_AUTOMATION -e TF_VAR_enable_telemetry -e AVM_MOD_PATH=/src -e AVM_EXAMPLE=${{ matrix.example }} \
+        #       -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_CLIENT_ID -e ARM_USE_MSI=true \
+        #       --env-file <(env | grep TF_VAR_ | grep -v ' "TF_VAR_"') mcr.microsoft.com/azterraform:latest make test-example
+        #     EOF
 
         # - name: Run Git Bash script
         #   shell: bash
